"""add_new_feature_v1

Revision ID: 793eefdcbfa6
Revises: dca439e092f7
Create Date: 2025-10-18 10:00:37.323289+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793eefdcbfa6'
down_revision: Union[str, None] = 'dca439e092f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
