"""baseline SSOT schema (2025-11-09)

Revision ID: c4ba0cb59598
Revises: 5004865355c9
Create Date: 2025-10-27 03:26:52.169718+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ba0cb59598'
down_revision: Union[str, None] = '5004865355c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_departments', schema=None) as batch_op:
        batch_op.drop_index('ix_departments_id')

    op.drop_table('master_departments')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index('ix_titles_id')

    op.drop_table('titles')
    op.drop_table('sales_front')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index('ix_department_id')

    op.drop_table('department')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_bank_code'), ['bank_code'], unique=False)
        batch_op.create_foreign_key(None, 'properties', ['property_code'], ['code'])
        batch_op.create_foreign_key(None, 'master_banks', ['bank_code'], ['code'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_dept_code'), ['dept_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    with op.batch_alter_table('employee_contracts', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_employee_contracts_id'), ['id'], unique=False)

    with op.batch_alter_table('master_banks', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    with op.batch_alter_table('master_hk_status', schema=None) as batch_op:
        batch_op.create_index('ix_hk_status_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_hk_status_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('uq_hk_status_code', ['code'])

    with op.batch_alter_table('master_property', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_master_property_code'), ['code'], unique=False)
        batch_op.create_index('ix_master_property_name', ['name'], unique=False)
        batch_op.create_unique_constraint('uq_master_property_code', ['code'])
        batch_op.drop_column('address')
        batch_op.drop_column('id')

    with op.batch_alter_table('master_titles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('order_no',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_master_titles_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('uq_master_titles_code', ['code'])
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('merge_batches', schema=None) as batch_op:
        batch_op.alter_column('missing_policy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('source_kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_index('ix_merge_batches_dataset_property', ['dataset', 'property_code'], unique=False)

    with op.batch_alter_table('merge_changelog', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dataset',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_merge_changelog_batch_id', ['batch_id'], unique=False)
        batch_op.create_index('ix_merge_changelog_dataset_property', ['dataset', 'property_code'], unique=False)

    with op.batch_alter_table('ota_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ota_channels_master_id'), ['master_id'], unique=False)

    with op.batch_alter_table('ota_orders', schema=None) as batch_op:
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index('ix_properties_code')
        batch_op.drop_index('ix_properties_name')
        batch_op.drop_constraint('uq_properties_code', type_='unique')

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('property_code')
        batch_op.drop_column('dataset')
        batch_op.drop_column('BOOLEAN')
        batch_op.drop_column('business_date')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('business_date', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('BOOLEAN', sa.NullType(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('dataset', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('property_code', sa.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_properties_code', ['code'])
        batch_op.create_index('ix_properties_name', ['name'], unique=False)
        batch_op.create_index('ix_properties_code', ['code'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('ota_orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('ota_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ota_channels_master_id'))

    with op.batch_alter_table('merge_changelog', schema=None) as batch_op:
        batch_op.drop_index('ix_merge_changelog_dataset_property')
        batch_op.drop_index('ix_merge_changelog_batch_id')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('dataset',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('batch_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('merge_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_merge_batches_dataset_property')
        batch_op.alter_column('source_kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('missing_policy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('master_titles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_master_titles_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_master_titles_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('order_no',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('master_property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_master_property_code', type_='unique')
        batch_op.drop_index('ix_master_property_name')
        batch_op.drop_index(batch_op.f('ix_master_property_code'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('master_hk_status', schema=None) as batch_op:
        batch_op.drop_constraint('uq_hk_status_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_master_hk_status_id'))
        batch_op.drop_index('ix_hk_status_name')

    with op.batch_alter_table('master_banks', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    with op.batch_alter_table('employee_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_contracts_id'))
        batch_op.alter_column('salary',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_dept_code'))

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bank_accounts_bank_code'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_code', sa.VARCHAR(length=10), server_default=sa.text("'MOP'"), nullable=False),
    sa.Column('dept_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dept_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('parent_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('leader_emp_id', sa.INTEGER(), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('order_no', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leader_emp_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index('ix_department_id', ['id'], unique=False)

    op.create_table('sales_front',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('business_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=100), nullable=True),
    sa.Column('amount', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('order_no', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index('ix_titles_id', ['id'], unique=False)

    op.create_table('master_departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_code', sa.VARCHAR(length=10), server_default=sa.text("'MOP'"), nullable=False),
    sa.Column('dept_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dept_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('parent_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('order_no', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('leader_emp_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['leader_emp_id'], ['employees.id'], name='fk_departments_leader_emp', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_departments', schema=None) as batch_op:
        batch_op.create_index('ix_departments_id', ['id'], unique=False)

    # ### end Alembic commands ###
