"""baseline v2025 clean

Revision ID: dca439e092f7
Revises: 
Create Date: 2025-10-18 09:59:21.075665+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca439e092f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.String(length=20), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_code', 'account_code', name='uq_bank_account')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_property_code'), ['property_code'], unique=False)

    op.create_table('bank_daily_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.String(length=20), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('closing_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_code', 'account_code', 'date', name='uq_bank_daily_balance')
    )
    with op.batch_alter_table('bank_daily_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_daily_balances_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_daily_balances_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_daily_balances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_daily_balances_property_code'), ['property_code'], unique=False)

    op.create_table('bank_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.String(length=20), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('txn_time', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=False),
    sa.Column('raw_ref', sa.String(length=255), nullable=False),
    sa.Column('dataset', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_txns', schema=None) as batch_op:
        batch_op.create_index('ix_bank_txn_key', ['property_code', 'account_code', 'txn_date', 'direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_dataset'), ['dataset'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_property_code'), ['property_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_txn_date'), ['txn_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_txns_version_no'), ['version_no'], unique=False)

    op.create_table('closing_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_code', 'business_date', name='uq_closing_day')
    )
    with op.batch_alter_table('closing_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closing_days_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_closing_days_property_code'), ['property_code'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.String(length=10), server_default='MOP', nullable=False),
    sa.Column('dept_code', sa.String(length=50), nullable=False),
    sa.Column('dept_name', sa.String(length=120), nullable=False),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('order_no', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dept', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('leave_date', sa.Date(), nullable=True),
    sa.Column('rrn_mask', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=60), nullable=False),
    sa.Column('account_mask', sa.String(length=60), nullable=False),
    sa.Column('account_last4', sa.String(length=8), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_emp_no'), ['emp_no'], unique=True)

    op.create_table('empno_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=20), server_default='EMP', nullable=False),
    sa.Column('start_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('auto_increment', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empno_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empno_policy_id'), ['id'], unique=False)

    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('k', sa.String(length=100), nullable=False),
    sa.Column('v', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'k', name='uq_keyword_group_key')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index('ix_keywords_active_weight', ['is_active', 'weight'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_group_name'), ['group_name'], unique=False)

    op.create_table('master_salary_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('annual_salary', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_salary_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_salary_grades_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_master_salary_grades_id'), ['id'], unique=False)

    op.create_table('merge_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=50), nullable=False),
    sa.Column('property_code', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('dry_run', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('missing_policy', sa.String(length=20), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merge_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merge_batches_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_batches_dataset'), ['dataset'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_batches_property_code'), ['property_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_batches_session_id'), ['session_id'], unique=False)

    op.create_table('ota_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ota_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ota_channels_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ota_channels_id'), ['id'], unique=False)

    op.create_table('ota_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('order_code', sa.String(length=80), nullable=False),
    sa.Column('guest_name', sa.String(length=120), nullable=True),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code', name='uq_ota_orders_order_code')
    )
    with op.batch_alter_table('ota_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ota_orders_channel'), ['channel'], unique=False)
        batch_op.create_index('ix_ota_orders_channel_status_created', ['channel', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_orders_check_in'), ['check_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_orders_check_out'), ['check_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_orders_order_code'), ['order_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_orders_status'), ['status'], unique=False)

    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_salary', sa.Integer(), server_default='0', nullable=True),
    sa.Column('order_no', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranks_id'), ['id'], unique=False)

    op.create_table('role_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=80), nullable=False),
    sa.Column('route_name', sa.String(length=120), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code', 'route_name', name='uq_role_access')
    )
    with op.batch_alter_table('role_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_access_role_code'), ['role_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_access_route_name'), ['route_name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)

    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('order_no', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_id'), ['id'], unique=False)

    op.create_table('upload_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=40), nullable=False),
    sa.Column('property_code', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_sessions_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_dataset'), ['dataset'], unique=False)
        batch_op.create_index('ix_upload_sessions_key', ['dataset', 'property_code', 'business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_property_code'), ['property_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('employee_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('pay_type', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('contract_no', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'version_no', name='uq_employee_contract_ver')
    )
    with op.batch_alter_table('employee_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_contracts_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'version_no', name='uq_employee_file_ver')
    )
    with op.batch_alter_table('employee_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_files_employee_id'), ['employee_id'], unique=False)

    op.create_table('fnb_items_canon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_on', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('last_batch_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_batch_id'], ['merge_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_fnb_items_canon_key_hash')
    )
    with op.batch_alter_table('fnb_items_canon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fnb_items_canon_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_fnb_items_canon_record_hash'), ['record_hash'], unique=False)
        batch_op.create_index('ix_fnb_items_canon_valid_on', ['valid_on'], unique=False)

    op.create_table('fnb_items_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_on', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_batch_id'], ['merge_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fnb_items_history', schema=None) as batch_op:
        batch_op.create_index('ix_fnb_items_history_batch', ['source_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fnb_items_history_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_fnb_items_history_record_hash'), ['record_hash'], unique=False)
        batch_op.create_index('ix_fnb_items_history_valid_on', ['valid_on'], unique=False)

    op.create_table('fnb_tenders_canon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_on', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('last_batch_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_batch_id'], ['merge_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_fnb_tenders_canon_key_hash')
    )
    with op.batch_alter_table('fnb_tenders_canon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fnb_tenders_canon_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_fnb_tenders_canon_record_hash'), ['record_hash'], unique=False)
        batch_op.create_index('ix_fnb_tenders_canon_valid_on', ['valid_on'], unique=False)

    op.create_table('fnb_tenders_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_on', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_batch_id'], ['merge_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fnb_tenders_history', schema=None) as batch_op:
        batch_op.create_index('ix_fnb_tenders_history_batch', ['source_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fnb_tenders_history_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_fnb_tenders_history_record_hash'), ['record_hash'], unique=False)
        batch_op.create_index('ix_fnb_tenders_history_valid_on', ['valid_on'], unique=False)

    op.create_table('merge_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('dataset', sa.String(length=50), nullable=True),
    sa.Column('property_code', sa.String(length=20), nullable=True),
    sa.Column('business_date', sa.String(length=20), nullable=True),
    sa.Column('key_hash', sa.String(length=128), nullable=True),
    sa.Column('record_hash', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('old_hash', sa.String(length=128), nullable=True),
    sa.Column('new_hash', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['merge_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ota_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['ota_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ota_commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ota_commissions_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index('ix_ota_commissions_channel_period', ['channel_id', 'valid_from', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_commissions_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_commissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_commissions_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_ota_commissions_valid_to'), ['valid_to'], unique=False)

    op.create_table('rooms_status_canon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_on', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('last_batch_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_batch_id'], ['merge_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_rooms_status_canon_key_hash')
    )
    with op.batch_alter_table('rooms_status_canon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_status_canon_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_status_canon_record_hash'), ['record_hash'], unique=False)
        batch_op.create_index('ix_rooms_status_canon_valid_on', ['valid_on'], unique=False)

    op.create_table('rooms_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_on', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_batch_id'], ['merge_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_rooms_status_history_batch', ['source_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_status_history_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_status_history_record_hash'), ['record_hash'], unique=False)
        batch_op.create_index('ix_rooms_status_history_valid_on', ['valid_on'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('part_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_uploaded_files_session_ver', ['session_id', 'version_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_version_no'), ['version_no'], unique=False)

    op.create_table('user_employee_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_single_map')
    )
    with op.batch_alter_table('user_employee_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_employee_map_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_employee_map_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    with op.batch_alter_table('user_employee_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_employee_map_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_employee_map_employee_id'))

    op.drop_table('user_employee_map')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_version_no'))
        batch_op.drop_index('ix_uploaded_files_session_ver')
        batch_op.drop_index(batch_op.f('ix_uploaded_files_session_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_created_at'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('rooms_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_status_history_valid_on')
        batch_op.drop_index(batch_op.f('ix_rooms_status_history_record_hash'))
        batch_op.drop_index(batch_op.f('ix_rooms_status_history_key_hash'))
        batch_op.drop_index('ix_rooms_status_history_batch')

    op.drop_table('rooms_status_history')
    with op.batch_alter_table('rooms_status_canon', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_status_canon_valid_on')
        batch_op.drop_index(batch_op.f('ix_rooms_status_canon_record_hash'))
        batch_op.drop_index(batch_op.f('ix_rooms_status_canon_key_hash'))

    op.drop_table('rooms_status_canon')
    with op.batch_alter_table('ota_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ota_commissions_valid_to'))
        batch_op.drop_index(batch_op.f('ix_ota_commissions_valid_from'))
        batch_op.drop_index(batch_op.f('ix_ota_commissions_id'))
        batch_op.drop_index(batch_op.f('ix_ota_commissions_effective_date'))
        batch_op.drop_index('ix_ota_commissions_channel_period')
        batch_op.drop_index(batch_op.f('ix_ota_commissions_channel_id'))

    op.drop_table('ota_commissions')
    op.drop_table('merge_changelog')
    with op.batch_alter_table('fnb_tenders_history', schema=None) as batch_op:
        batch_op.drop_index('ix_fnb_tenders_history_valid_on')
        batch_op.drop_index(batch_op.f('ix_fnb_tenders_history_record_hash'))
        batch_op.drop_index(batch_op.f('ix_fnb_tenders_history_key_hash'))
        batch_op.drop_index('ix_fnb_tenders_history_batch')

    op.drop_table('fnb_tenders_history')
    with op.batch_alter_table('fnb_tenders_canon', schema=None) as batch_op:
        batch_op.drop_index('ix_fnb_tenders_canon_valid_on')
        batch_op.drop_index(batch_op.f('ix_fnb_tenders_canon_record_hash'))
        batch_op.drop_index(batch_op.f('ix_fnb_tenders_canon_key_hash'))

    op.drop_table('fnb_tenders_canon')
    with op.batch_alter_table('fnb_items_history', schema=None) as batch_op:
        batch_op.drop_index('ix_fnb_items_history_valid_on')
        batch_op.drop_index(batch_op.f('ix_fnb_items_history_record_hash'))
        batch_op.drop_index(batch_op.f('ix_fnb_items_history_key_hash'))
        batch_op.drop_index('ix_fnb_items_history_batch')

    op.drop_table('fnb_items_history')
    with op.batch_alter_table('fnb_items_canon', schema=None) as batch_op:
        batch_op.drop_index('ix_fnb_items_canon_valid_on')
        batch_op.drop_index(batch_op.f('ix_fnb_items_canon_record_hash'))
        batch_op.drop_index(batch_op.f('ix_fnb_items_canon_key_hash'))

    op.drop_table('fnb_items_canon')
    with op.batch_alter_table('employee_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_files_employee_id'))

    op.drop_table('employee_files')
    with op.batch_alter_table('employee_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_contracts_employee_id'))

    op.drop_table('employee_contracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_sessions_property_code'))
        batch_op.drop_index('ix_upload_sessions_key')
        batch_op.drop_index(batch_op.f('ix_upload_sessions_dataset'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_business_date'))

    op.drop_table('upload_sessions')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_id'))

    op.drop_table('titles')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('role_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_access_route_name'))
        batch_op.drop_index(batch_op.f('ix_role_access_role_code'))

    op.drop_table('role_access')
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranks_id'))

    op.drop_table('ranks')
    with op.batch_alter_table('ota_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ota_orders_status'))
        batch_op.drop_index(batch_op.f('ix_ota_orders_order_code'))
        batch_op.drop_index(batch_op.f('ix_ota_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_ota_orders_check_out'))
        batch_op.drop_index(batch_op.f('ix_ota_orders_check_in'))
        batch_op.drop_index('ix_ota_orders_channel_status_created')
        batch_op.drop_index(batch_op.f('ix_ota_orders_channel'))

    op.drop_table('ota_orders')
    with op.batch_alter_table('ota_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ota_channels_id'))
        batch_op.drop_index(batch_op.f('ix_ota_channels_code'))

    op.drop_table('ota_channels')
    with op.batch_alter_table('merge_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merge_batches_session_id'))
        batch_op.drop_index(batch_op.f('ix_merge_batches_property_code'))
        batch_op.drop_index(batch_op.f('ix_merge_batches_dataset'))
        batch_op.drop_index(batch_op.f('ix_merge_batches_business_date'))

    op.drop_table('merge_batches')
    with op.batch_alter_table('master_salary_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_salary_grades_id'))
        batch_op.drop_index(batch_op.f('ix_master_salary_grades_code'))

    op.drop_table('master_salary_grades')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_group_name'))
        batch_op.drop_index('ix_keywords_active_weight')

    op.drop_table('keywords')
    with op.batch_alter_table('empno_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empno_policy_id'))

    op.drop_table('empno_policy')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_emp_no'))
        batch_op.drop_index(batch_op.f('ix_employees_deleted_at'))

    op.drop_table('employees')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('closing_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closing_days_property_code'))
        batch_op.drop_index(batch_op.f('ix_closing_days_business_date'))

    op.drop_table('closing_days')
    with op.batch_alter_table('bank_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_txns_version_no'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_txn_date'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_session_id'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_property_code'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_direction'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_dataset'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_created_at'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_business_date'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_amount'))
        batch_op.drop_index(batch_op.f('ix_bank_txns_account_code'))
        batch_op.drop_index('ix_bank_txn_key')

    op.drop_table('bank_txns')
    with op.batch_alter_table('bank_daily_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_daily_balances_property_code'))
        batch_op.drop_index(batch_op.f('ix_bank_daily_balances_date'))
        batch_op.drop_index(batch_op.f('ix_bank_daily_balances_created_at'))
        batch_op.drop_index(batch_op.f('ix_bank_daily_balances_account_code'))

    op.drop_table('bank_daily_balances')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_property_code'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_created_at'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_account_code'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
